#ifndef _3DEYE_COMMON_H_
#define _3DEYE_COMMON_H_

#define IN_WIDTH 320
#define IN_HEIGHT 240
#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800
#define WIDTH SCREEN_WIDTH
#define HEIGHT SCREEN_HEIGHT
#define DEBUG 0

#define LEFT_X_OFFSET -SCREEN_WIDTH
#define RIGHT_X_OFFSET 1440
#define MONITOR_X_OFFSET 0

#endif
